BlueBikes Linear Regression

Loading packages

```{r}
#install.packages("tidyverse")
library(tidyr) 
library(dplyr) 
library(ggplot2)
#install.packages("tmap", repos = c("https://r-tmap.r-universe.dev",
                                  # "https://cloud.r-project.org"))
library(sf)
library(terra)
library(dplyr)
library(tmap)    
library(leaflet)

library(caTools)
library(readr)
library(downloader)
library(caTools)
library(FNN)
library(readxl)

library(lubridate)

library(digest)

#install.packages("factoextra")
library(factoextra)

install.packages("bigmemory")
library(bigmemory)
```

Loading dataset

```{r}
# read in dataset
file_name <- list.files("data")
data_original <- read.csv(paste0("data/",file_name))
data_original
```

Add column: total trip time

```{r}
times <- mutate(data_original, trip_time = difftime(ended_at,started_at, units = "mins"))
head(times)
```

Creating new datasets with relevant columns only

```{r}
# all relevant columns
rel_data <- select(times,"ride_id","rideable_type","trip_time","start_station_id", "end_station_id")

# type of bike and trip time
bike_time <- select(times,"rideable_type","trip_time")

# type of bike and stations
bike_station <- select(times,"rideable_type","start_station_id", "end_station_id")

# trip time and stations
time_station <- select(times,"trip_time","start_station_id", "end_station_id")

#locations
start_locations <- select(times,"start_station_id","start_lat","start_lng")

#head(rel_data)
#bike_time
#head(bike_station)
#head(time_station)
#head(start_locations)
```

Converting all data into numerical values!

```{r}
#date_time
#days
num_data <- data_frame(rideable_type = date_time$rideable_type, 
                       start_time = date_time$start_time, 
                       start_weekday = days$start_weekday, 
                       end_weekday = days$end_weekday, 
                       start_station_id = date_time$start_station_id, 
                       end_station_id = date_time$end_station_id,
                       start_lat = date_time$start_lat,
                       start_lng = date_time$start_lng,
                       end_lat = date_time$end_lat,
                       end_lng = date_time$end_lng,
                       member_casual = times$member_casual,
                       trip_time = date_time$trip_time)

#head(num_data)

#making rideable type numerical
num_data <- mutate(num_data, classic_bike = ifelse(rideable_type=="classic_bike", 1, 0),
         electric_bike = ifelse(rideable_type=="electric_bike", 1, 0))

#making start_weekday numerical
num_data <- mutate(num_data, sun = ifelse(start_weekday=="Sunday", 1, 0),
                   mon = ifelse(start_weekday=="Monday", 1, 0),
                   tue = ifelse(start_weekday=="Tuesday", 1, 0),
                   wed = ifelse(start_weekday=="Wednesday", 1, 0),
                   thu = ifelse(start_weekday=="Thursday", 1, 0),
                   fri = ifelse(start_weekday=="Friday", 1, 0),
                   sat = ifelse(start_weekday=="Saturday", 1, 0))

#making member_casual numerical
num_data <- mutate(num_data, member = ifelse(member_casual=="member", 1, 0),
                   casual = ifelse(member_casual=="casual", 1, 0))

#making start_time numerical
num_data <- mutate(num_data, start_timeform=hms(num_data$start_time))

#making start_station_id numerical
#id_to_crc32 <- function(id) {return(as.numeric(crc32(id)))}

#num_data <- mutate(num_data, start_station_id_hashed =
                     #sapply(num_data$start_station_id, id_to_crc32))

id_to_crc32 <- function(id) {
  hash_value <- digest(id, algo = "crc32", serialize = FALSE)
  return(as.numeric(paste0("0x", hash_value)))
}

# Apply the function to hash the start_station_id column
num_data <- mutate(num_data, start_station_id_hashed = sapply(start_station_id, id_to_crc32))

# Apply the function to hash the start_station_id column
num_data <- mutate(num_data, end_station_id_hashed = sapply(end_station_id, id_to_crc32))
```

Making final dataset

```{r}
#making time ranges
start <- 0
end <- 1500
interval <- 5

ranges <- sapply(seq(start, end - interval, by = interval), function(x) {
  paste(x, x + interval, sep = "-")
})

#print(ranges)

#defining the time ranges
numsfive <- seq(from = 0, to = 1500, by = 5)

#print(numsfive)
```

```{r}
conv_data <- select(num_data, 7:10, 13:26)

data_original %>% 
  mutate(started_at=parse_date_time(started_at, "Ymd HMS"),
    start_hour=hour(started_at))

final_data <- data_frame(
  sun = conv_data$sun,
  sat = conv_data$sat,
  classic_bike = conv_data$classic_bike,
  weekend = ifelse(conv_data$sat == 1 | conv_data$sun == 1, 1, 0),
  member = conv_data$member,
  casual = conv_data$casual,
  start_station_id_hash = conv_data$start_station_id_hashed,
  end_station_id_hash = conv_data$start_station_id_hashed,
  start_hour = hour(conv_data$start_timeform),
  trip_time = ifelse(round(times$trip_time, digits = 0) <= 30, round(times$trip_time, digits = 0), NA))

final_data$trip_time <- as.numeric(final_data$trip_time)

final_data$trip_time <- cut(final_data$trip_time, breaks = numsfive, labels = ranges, include.lowest = TRUE)

final_data$trip_time <- as.numeric(final_data$trip_time)

final_data <- na.omit(final_data)

final_data
```

KNN Model

Dataset

```{r}
head(final_data)
unique(final_data$trip_time)
```

Splitting the Data

```{r}
set.seed(123)

split <- sample.split(final_data$trip_time, SplitRatio = 0.8)
train_data <- subset(final_data, split == TRUE)
test_data <- subset(final_data, split == FALSE)
```

Fitting the Model

```{r}
lr_model <- lm(trip_time ~ start_station_id_hash+start_hour, 
data = train_data)
```

Testing the Model

```{r}
pred <- predict(lr_model, newdata = test_data)
```

Evaluating the Model

```{r}
mse <- mean((test_data$trip_time - pred)^2, na.rm = TRUE) 
mae <- mean(abs(test_data$trip_time - pred), na.rm = TRUE) 
r_squared <- summary(lr_model)$r.squared
mse
mae
r_squared
```

```{r}
ggplot(test_data, aes(x = trip_time, y = pred)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Real vs Predicted Values",
       x = "True Trip Time",
       y = "Predicted Trip Time")
```
