```{r}
library(titanic)
library(dplyr)
library(janitor)
library(ggplot2)
library(tidyr)
library(readr)
library(lubridate)
library(maps)
library(ggmap)
library(sp)
library(leaflet)
library(geosphere)
#read in dataset
file_name <- list.files("data")
data <- read.csv("/Users/reddy/Documents/DSRP-Dataset/bluebikes/data/202406-bluebikes-tripdata.csv")
head(data)
dim(data)
str(data)
```

```{r}
data_clean <- drop_na(remove_empty(data, c("rows", "cols")))
dim(data_clean)
```

```{r}
ggplot(data_time_sep, aes(x=member_casual, y=mean(ride_time_mins)))+
  geom_bar(stat='identity')

```

Heatmap of bike type and member type

```{r}
data_agg <- data_clean %>%
  group_by(rideable_type, member_casual) %>%
  summarise(count = n())

ggplot(data_agg, aes(x = rideable_type, y = member_casual, fill = count)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "gray", high = "darkblue") +
  labs(title = "Tile Plot of Member Type vs Rideable Type",
       x = "Rideable Type",
       y = "Member Type") +
  theme_minimal()
```

histogram of where bikes ended

```{r}
data_slice_50 <- slice_head(arrange(data_clean,started_at), n=50)
ggplot(data_slice_50, aes(x = end_station_name)) +
  geom_bar(fill = "skyblue", color = "black") +
  labs(title = "Count of Bike Rides Ending at Each Station",
       x = "End Station Name",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

histogram of where bikes started

```{r}
data_slice_50 <- slice_head(arrange(data_clean,started_at), n=50)
ggplot(data_slice_50, aes(x = start_station_name)) +
  geom_bar(fill = "skyblue", color = "black") +
  labs(title = "Count of Bike Rides Ending at Each Station",
       x = "End Station Name",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
